### ISSUE TITLE
Failed to run on openSUSE Leap 15.2

### ISSUE THREAD

**Issue by dantalian-pv** [diviks2008/MyFM#1]
When running on openSUSE Leap 15.2 with python3, the application fails with the next error message:
```
~> python3 MyFM_PFT_win2.py 
Traceback (most recent call last):
  File "MyFM_PFT_win2.py", line 660, in <module>
    MyFM_PFT_v2()
  File "MyFM_PFT_win2.py", line 644, in MyFM_PFT_v2
    app = App(root)
  File "MyFM_PFT_win2.py", line 127, in __init__
    self.insert_in_tree()
  File "MyFM_PFT_win2.py", line 178, in insert_in_tree
    m = magic.Magic(mime=True)
TypeError: __init__() got an unexpected keyword argument 'mime'
```

Seems like incompatible `magic` library versions. I have the next installed python3 packages (related to the app):

- python3-Pillow-tk-5.0.0-lp152.4.1.x86_64
- python3-magic-5.32-lp152.9.1.x86_64
- python3-tk-3.6.10-lp152.4.6.2.x86_64
- python3-Pillow-5.0.0-lp152.4.1.x86_64

Would be nice, either to consider which library versions should be used or to make code compatible with provided versions.

**Comment by diviks2008** [comment]
Before starting the program, you must install:
python3-tk python3-magic python3-pil python3-pil.imagetk

Example for Debian, Ubuntu:
sudo apt install python3-tk python3-magic python3-pil python3-pil.imagetk

**Comment by diviks2008** [comment]
Installation example for Opensuse:
sudo zypper install python3-tk python3-magic python3-Pillow python3-Pillow-tk

**Comment by diviks2008** [comment]
Before starting the program, you must install:
python3-tk python3-magic python3-pil python3-pil.imagetk

Example for Debian, Ubuntu:
sudo apt install python3-tk python3-magic python3-pil python3-pil.imagetk

**Comment by diviks2008** [comment]
in OpenSuse the program gives an error, because Python versions and dependencies do not match.
The problem may be resolved by switching to the appropriate version of the dependencies.

**Comment by dantalian-pv** [comment]
Which dependencies versions are appropriate?

**Comment by diviks2008** [comment]
for debian:
python3-tk/stable,now 3.7.3-1 amd64
python3-magic/stable,now 2:0.4.15-2
python3-pil/stable,now 5.4.1-2+deb10u2 amd64 
python3-pil.imagetk/stable,now 5.4.1-2+deb10u2 amd64

**Comment by diviks2008** [comment]
for ubuntu:
python3-tk/focal-updates,focal-security,now 3.8.5-1~20.04.1 amd64
python3-magic/focal,focal,now 2:0.4.15-3
python3-pil/focal-updates,focal-security,now 7.0.0-4ubuntu0.1 amd64
python3-pil.imagetk/focal-updates,focal-security,now 7.0.0-4ubuntu0.1 amd64

**Comment by diviks2008** [comment]
for Kubuntu:
python3-tk/focal,now 3.8.2-1ubuntu1 amd64
python3-magic/focal,now 2:0.4.15-3
python3-pil.imagetk/focal-security,focal-updates,now 7.0.0-4ubuntu0.1 amd64
python3-pil/focal-security,focal-updates,now 7.0.0-4ubuntu0.1 amd64

**Comment by diviks2008** [comment]
For OpenSuse:
sudo zypper install python3-tk python3-python-magic python3-Pillow python3-Pillow-tk

In console for clearing out the X resources:
xrdb -load /dev/null
xrdb -query

Or install python3-magic:
sudo zypper remove python3-magic
sudo zypper install python3-python-magic
